Funssignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('account/',include('users.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('password-change/',auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),name='password_change'),
    path('password-change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),name='password_change_done'),
]


urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

handler404 = "Funssignment.views.page_not_found_view"

index/urls.py
from django.urls import path
from . import views

app_name='index'

urlpatterns = [
    path('',views.index,name='index'),
    path('rules/',views.rules,name='rules'),
    path('quiz/<str:title>/',views.paginated_quiz,name='paginated_quiz'),
    path('mock/<int:post_id>/',views.quiz,name='quiz'),
    path('search/',views.search,name='search'),
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('contact/',views.contact,name='contact'),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.logout,name='logout'),
    path('profile-update/',views.profile_update,name='profile-update')
]

index/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock title %} </title>
    {% block script %} {% endblock script %}
    <style>
      @media screen and (max-width:640px) {
        .funssignment{
          position:absolute;
          left:250px;
        }
        .funssignmentimg{
          position:relative;
          left:240px;
        }
      }

      @media screen and (max-width:570px) {
        .funssignment{
          position:absolute;
          left:230px;
        }
        .funssignmentimg{
          position:relative;
          left:220px;
        }
      }
      @media screen and (max-width:540px) {
        .funssignment{
          position:absolute;
          left:220px;
        }
        .funssignmentimg{
          position:relative;
          left:210px;
        }
      }
      @media screen and (max-width:520px) {
        .funssignment{
          position:absolute;
          left:200px;
        }
        .funssignmentimg{
          position:relative;
          left:190px;
        }
      }
      @media screen and (max-width:420px) {
        .funssignment{
          position:absolute;
          left:150px;
        }
        .funssignmentimg{
          position:relative;
          left:140px;
        }
      }
     
      @media screen and (max-width:390px) {
        .funssignment{
          position:absolute;
          left:130px;
        }
        .funssignmentimg{
          position:relative;
          left:120px;
        }
      }
      @media screen and (max-width:350px) {
        html{
          font-size:90%;
        }
        .funssignment{
          position:absolute;
          left:110px;
        }
        .funssignmentimg{
          position:relative;
          left:100px;
        }
      }

      @media screen and (max-width:300px) {
        html{
          font-size:80%;
        }
        .funssignment{
          position:absolute;
          left:100px;
          margin-bottom:10px;
        }
        .funssignmentimg{
          position:relative;
          left:90px;
        }
        .nav-div{
          margin-top:10px;
        }
      }
    </style>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" integrity="sha512-wnea99uKIC3TJF7v4eKk4Y+lMz2Mklv18+r4na2Gn1abDRPPOeef95xTzdwGD9e6zXJBteMIhZ1+68QC5byJZw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

<!-- component -->
<nav class="font-sans flex flex-col text-center content-center sm:flex-row sm:text-left sm:justify-between py-2 px-6 bg-white shadow sm:items-baseline w-full">
    <div class="mb-2 sm:mb-0 inner">
  
      <a href="" class="no-underline font-sans font-bold"><img class="h-10 w-10 ml-8 mb-2 funssignmentimg" src="{% static 'images/funssignment.png' %}" alt=""></a><br>
      <span class="text-xl text-grey-dark funssignment" style="position:absolute; top:50px;">Funssignment</span>
  
    </div>
  
    <div class="sm:mb-0 self-center nav-div">
      <!-- <div class="h-10" style="display: table-cell, vertical-align: middle;"> -->
      <a href="{% url 'index:index' %}" class="text-md no-underline text-black hover:text-blue-dark ml-2 px-1">Home</a>
      {% if user.is_authenticated %}
      <a href="{% url 'users:contact' %}" class="text-md no-underline text-grey-darker hover:text-blue-dark ml-2 px-1">Contact</a>
      {% else %}
      <a href="{% url 'login' %}" class="text-md no-underline text-grey-darker hover:text-blue-dark ml-2 px-1">Contact</a>
      {% endif %}
      {% if user.is_authenticated %}
      <a href="{% url 'users:profile' %}" class="text-md no-underline text-grey-darker hover:text-blue-dark ml-2 px-1">Profile</a>
      {% else %}
      <a href="{% url 'login' %}" class="text-md no-underline text-grey-darker hover:text-blue-dark ml-2 px-1">Profile</a>
      {% endif %}
      <!-- <a href="/two" class="text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2">About Us</a> -->
      {% if user.is_authenticated %}
      <a href="{% url 'users:logout' %}" class="text-md no-underline text-grey-darker hover:text-blue-dark ml-2 px-1">Logout</a>
      {% else %}
      <a href="{% url 'login' %}" class="text-md no-underline text-grey-darker hover:text-blue-dark ml-2 px-1">Login</a>
      {% endif %}
      <!-- </div> -->
    </div>
  </nav>
  {% block body %} {% endblock body  %}

  </body>
  </html>

index/templates/error404.html
<!-- component -->
<!DOCTYPE html>
<html>
<head>
<title>404 Error Page Design In Tailwind CSS</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300i,400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<style type="text/css">
      .text-9xl{
      font-size: 14rem;
      }
      @media(max-width: 645px){
      .text-9xl{
      font-size: 5.75rem;
      }
      .text-6xl{
      font-size: 1.75rem;
      }
      .text-2xl {
      font-size: 1rem;
      line-height: 1.2rem;
      }
      .py-8 {
      padding-top: 1rem;
      padding-bottom: 1rem;
      }
      .px-6 {
      padding-left: 1.2rem;
      padding-right: 1.2rem;
      }
      .mr-6{
      margin-right: 0.5rem;
      }
      .px-12 {
      padding-left: 1rem;
      padding-right: 1rem;
      }
      }
    </style>
</head>
<body>
<div class="bg-gradient-to-r from-purple-300 to-blue-200">
<div class="w-9/12 m-auto py-16 min-h-screen flex items-center justify-center">
<div class="bg-white shadow overflow-hidden sm:rounded-lg pb-8">
<div class="border-t border-gray-200 text-center pt-8">
<h1 class="text-9xl font-bold text-purple-400">404</h1>
<h1 class="text-6xl font-medium py-8">oops! Page not found</h1>
<p class="text-2xl pb-8 px-12 font-medium">Oops! The page you are looking for does not exist. It might have been moved or deleted.</p>
<button class="bg-gradient-to-r from-purple-400 to-blue-500 hover:from-pink-500 hover:to-orange-500 text-white font-semibold px-6 py-3 rounded-md mr-6">
HOME
</button>
<button class="bg-gradient-to-r from-red-400 to-red-500 hover:from-red-500 hover:to-red-500 text-white font-semibold px-6 py-3 rounded-md">
  </a>
Contact Us
</button>
</div>
</div>
</div>
</div>
</body>
</html>