Funssignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('account/',include('users.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('password-change/',auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),name='password_change'),
    path('password-change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),name='password_change_done'),
]


urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

handler404 = "Funssignment.views.page_not_found_view"

index/urls.py
from django.urls import path
from . import views

app_name='index'

urlpatterns = [
    path('',views.index,name='index'),
    path('rules/',views.rules,name='rules'),
    path('quiz/<str:title>/',views.paginated_quiz,name='paginated_quiz'),
    path('mock/<int:post_id>/',views.quiz,name='quiz'),
    path('search/',views.search,name='search'),
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('contact/',views.contact,name='contact'),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.logout,name='logout'),
    path('profile-update/',views.profile_update,name='profile-update')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import validate_image_file_extension
from PIL import Image
from django.dispatch import receiver 
from django.db.models.signals import post_save


class Contact(models.Model):
    name=models.CharField(max_length=120,null=False,blank=False)
    subject=models.CharField(max_length=100,null=False,blank=False)
    message=models.TextField(null=False,blank=False)
    contacted_by=models.ForeignKey(User,on_delete=models.CASCADE,null=False,blank=False)
    contacted_on=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

gender_choices = {
    ("Male","Male"),
    ("Female","Female"),
}


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='default.jpeg',upload_to='Profile_Pics',blank=True,null=False,validators=[validate_image_file_extension])
    about=models.TextField(blank=True,default='About Section')
    phone_no=models.CharField(max_length=10,blank=True,null=True)
    gender = models.CharField(max_length=20, choices=gender_choices,blank=True)
    
    def __str__(self):
        return  str(self.user)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.height <300 or img.width > 300 or img.width <300:
            output_size = (282, 282)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        fields=['about','image','phone_no','gender']
        model=Profile

users/views.py
from django.shortcuts import get_object_or_404, render,HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout as django_logout
import datetime
from .models import Contact,Profile
from .forms import ProfileForm

def register(request):
    if request.method=='POST':
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        confirm_password=request.POST.get('confirm_password')
        if password==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username Taken')
                return render(request,'users/signup.html')
            elif len(password) <8:
                messages.info(request,'ATLEAST 8 CHARACTER PASSWORD NEEDED')
                return render(request,'users/signup.html')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'Email Taken')
                return render(request,'users/signup.html')
            else:
                entry=User.objects.create_user(username=username,email=email,password=password)
                entry.save()
                messages.success(request,'Account Created!')
                return HttpResponseRedirect(reverse('login'))
        else:
            messages.info(request,'Password and confirm password didn"t match')
    return render(request,'users/signup.html')


@login_required
def contact(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        subject=request.POST.get('subject')
        message=request.POST.get('message')
        contacted_by=request.user
        contacted_on=datetime.datetime.now()
        contact_entry=Contact(name=name,subject=subject,message=message,contacted_by=contacted_by,contacted_on=contacted_on)
        contact_entry.save()
        messages.success(request,'THANKS FOR CONTACTING US! WE WILL REACH TO U ASAP')
        return HttpResponseRedirect(reverse('index:index'))
    return render(request,'users/contact.html')


@login_required
def profile(request):
    pqueryset=Profile.objects.filter(user=request.user)
    return render(request,'users/profile.html',{'pqueryset':pqueryset})

@login_required
def profile_update(request):
    #queryset_update=Profile.objects.get(user=request.user)
    queryset_update=get_object_or_404(Profile,user=request.user)
    form = ProfileForm(request.POST or None, instance = queryset_update)
    if form.is_valid():
        form.save()
        messages.success(request,'Updated!')
        return HttpResponseRedirect(reverse('users:profile'))
    return render(request,'index/profile_update.html',{'queryset_update':queryset_update,'form':form})

@login_required
def logout(request):
    django_logout(request)
    messages.info(request,'You have been logged out')
    return HttpResponseRedirect(reverse('login'))

users/templates/users/after-reset.html
{% extends "base.html" %}
{% block title %} Reset {% endblock title %}
{% block body %}
{% load tailwind_filters %}

<div class="flex flex-col items-center pt-12 w-screen h-screen bg-gray-200 text-

gray-700">
        <form class="flex flex-col bg-white rounded shadow-lg p-12" action="">
            {% csrf_token %}
            {{form|crispy}}
                <label class="font-semibold text-xs" 

for="usernameField">Password</label>
                <input class="flex items-center h-12 px-4 w-64 bg-gray-200 mt-2 rounded 

focus:outline-none focus:ring-2" type="password">

<label class="font-semibold text-xs" for="usernameField">Confirm Password</label>
                <input class="flex items-center h-12 px-4 w-64 bg-gray-200 mt-2 rounded 

focus:outline-none focus:ring-2" type="password">
               
            <button class="flex items-center justify-center h-12 px-6 w-100 bg-blue-600 

mt-8 rounded font-semibold text-sm text-blue-100 hover:bg-blue-700">Reset</button>
            <div class="flex mt-6 justify-center text-xs">
            <a class="text-blue-400 hover:text-blue-500" href="#">Login</a>
                <span class="mx-2 text-grey-300">/</span>
                <a class="text-blue-400 hover:text-blue-500" href="#">Sign Up</a>
            </div>
        </form>
        <!-- Component End  -->
    
    </div>

{% endblock body %}

users/templates/users/contact.html
{% extends "base.html" %}
{% block title %} Contact {% endblock title %}
{% block body %}
    <!-- component -->
<!-- This is an example component -->

    <div class="flex flex-col items-center pt-5 w-screen h-screen bg-gray-200 text-gray-700">
        {% if messages %}
        <div class="max-w-lg mx-auto">
            <div class="flex bg-yellow-100 rounded-lg p-4 mb-4 text-sm text-yellow-700" role="alert">
                <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                <div>
                    {% for msg in messages %}
                    <span class="font-medium">Info!</span>{{msg}}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <form class="flex flex-col bg-white rounded shadow-lg p-12" method="post">
          {% csrf_token %}
                    <label class="font-semibold text-xs text-left" for="name">Name</label>
                    <input class="flex items-center h-12 px-2 w-64 bg-gray-200 mt-2 mb-4 rounded focus:outline-none focus:ring-2" type="text" name="name" >
                     <label class="font-semibold text-xs text-left" for="subject">Subject/Issue</label>
                    <input class="flex items-center h-12 px-2 w-64 bg-gray-200 mt-2 mb-4 rounded focus:outline-none focus:ring-2" type="text" name="subject" >
    
                     <label class="font-semibold text-xs text-left" for="message">Message</label>
                    <textarea class="flex items-center h-32 px-2 w-64 bg-gray-200 mt-2 rounded focus:outline-none focus:ring-2" name="message" ></textarea>          
            
            <button class="flex items-center justify-center h-12 px-6 w-64 bg-blue-600 mt-8 rounded font-semibold text-sm text-blue-100 hover:bg-blue-700">Submit</button>
        </form>
    </div>
{% endblock body %}

users/templates/users/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock title %}
{% block body %}
{% load tailwind_filters %}

    <div class="flex flex-col items-center pt-12 w-screen h-screen bg-gray-200 text-gray-700">
        {% if messages %}
        <div class="max-w-lg mx-auto">
            <div class="flex bg-yellow-100 rounded-lg p-4 mb-4 text-sm text-yellow-700" role="alert">
                <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                <div>
                    {% for msg in messages %}
                    <span class="font-medium">Info! </span>{{msg}}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <form class="flex flex-col bg-white rounded shadow-lg p-12" method="POST">
          {% csrf_token %}
          {{ form|crispy }}
            <button class="flex items-center justify-center h-12 px-6 w-64 bg-blue-600 mt-8 rounded font-semibold text-sm text-blue-100 hover:bg-blue-700">Login</button>
            <div class="flex mt-6 justify-center text-xs">
            <a class="text-blue-400 hover:text-blue-500" href="{% url 'password_reset' %}">Forgot Password</a>
                <span class="mx-2 text-grey-300">/</span>
                <a class="text-blue-400 hover:text-blue-500" href="{% url 'users:register' %}">Sign Up</a>
            </div>
        </form>
    </div>
{% endblock body %}

users/templates/users/password_change.html
{% extends "base.html" %}
{% block title %} Change Password {% endblock title %}
{% block body %}
{% load tailwind_filters %}

<div class="flex flex-col items-center pt-12 w-screen h-screen bg-gray-200 text-gray-700">
    {% if messages %}
    <div class="max-w-lg mx-auto">
        <div class="flex bg-yellow-100 rounded-lg p-4 mb-4 text-sm text-yellow-700" role="alert">
            <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <div>
                {% for msg in messages %}
                <span class="font-medium">Info!</span>{{msg}}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}

    <form class="flex flex-col bg-white rounded shadow-lg p-12" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="flex items-center justify-center h-12 px-6 w-100 bg-blue-600 mt-8 rounded font-semibold text-sm text-blue-100 hover:bg-blue-700">Reset</button>
        <div class="flex mt-6 justify-center text-xs">
            <a class="text-blue-400 hover:text-blue-500" href="{% url 'login' %}">Login</a>
            <span class="mx-2 text-grey-300">/</span>
            <a class="text-blue-400 hover:text-blue-500" href="{% url 'users:register' %}">Sign Up</a>
        </div>
    </form>
    <!-- Component End  -->
</div>
{% endblock body %}

users/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %} Password Change Done {% endblock title %}
{% block body %}


<div class="mt-5">
    <h1 class="flex justify-center items-center align-center text-3xl text-green-500 mb-3">Password Changed Successfully!!</h1>
    <a href="{% url 'users:profile' %}" class=" flex justify-center items-center align-center text-xl text-blue-500"><button class="form__button" >Back to Profile</button></a>

  
</div>
   


{% endblock body %}

users/templates/users/password_reset.html
{% extends "base.html" %}
{% block title %} Reset {% endblock title %}
{% block body %}
{% load tailwind_filters %}


    <div class="flex flex-col items-center pt-12 w-screen h-screen bg-gray-200 text-gray-700">
        {% if messages %}
        <div class="max-w-lg mx-auto">
            <div class="flex bg-yellow-100 rounded-lg p-4 mb-4 text-sm text-yellow-700" role="alert">
                <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                <div>
                    {% for msg in messages %}
                    <span class="font-medium">Info!</span>{{msg}}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <form class="flex flex-col bg-white rounded shadow-lg p-10" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="flex items-center justify-center h-12 px-6 w-64 bg-blue-600 mt-8 rounded font-semibold text-sm text-blue-100 hover:bg-blue-700">Reset</button>
            <div class="flex mt-6 justify-center text-xs">
            <a class="text-blue-400 hover:text-blue-500" href="{% url 'login' %}">Login</a>
                <span class="mx-2 text-grey-300">/</span>
                <a class="text-blue-400 hover:text-blue-500" href="{% url 'users:register' %}">Sign Up</a>
            </div>
        </form>
        <!-- Component End  -->
    </div>
{% endblock body %}

users/templates/users/password_reset_complete.html
{% extends "index/base.html" %}
{% block title %} Reset Done {% endblock title %}
{% block body %}
        
            <h1 class="form__title">Your Password has been successfully reset!</h1>
            
            <a href="{% url 'login' %}"><button class="form__button" >Login!</button></a> 
{% endblock body %}

users/templates/users/password_reset_confirm.html
{% extends "index/base.html" %}
{% block title %} New Password {% endblock title %}
{% block body %}
{% load crispy_forms_tags %}
        
        <form class="form" id="login" method="post">
            {% csrf_token %}
            <h1 class="form__title">Reset Password</h1>
            <div class="form__message form__message--error">
            {% if messages %}
            {% for msg in messages %}
            <p>{{msg}}</p>
            {% endfor %}
            {% else %}
            <p>Access to the most powerfull tool in the entire design and web industry.</p>
            {% endif %}
            </div>
            <div class="form__input-group">
                {{form |crispy}}
                <div class="form__input-error-message"></div>
            </div>
            <button class="form__button" type="submit">Continue</button>
        </form>        
{% endblock body %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %} Reset Done {% endblock title %}
{% block body %}

        
<div class="mt-5">
     <h1 class="flex justify-center items-center align-center text-3xl text-gray-500">Reset Password Link Sent.Check mail !</h1>
     <h2 class="flex justify-center items-center align-center text-3xl text-gray-500 mb-3">Didn't recieve email/Entered wrong email?</h2>
     <a href="{% url 'password_reset' %}" class=" flex justify-center items-center align-center text-xl text-blue-500"><button class="form__button" >Resend Email</button></a>
</div>
    
     
            
           
{% endblock body %}

users/templates/users/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock title %}
{% block body %}  

    <div class="bg-gray-100">
 <div class="w-full text-white bg-main-color">
        <div x-data="{ open: false }"
            class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
            <div class="p-6 flex flex-row items-center justify-between">
               
                <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
                    <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                        <path x-show="!open" fill-rule="evenodd"
                            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"
                            clip-rule="evenodd"></path>
                        <path x-show="open" fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
    <!-- End of Navbar -->

    <div class="container mx-auto my-5 p-5">
        <div class="md:flex no-wrap md:-mx-2 ">
            <!-- Left Side -->
            <div class="w-full md:w-3/12 md:mx-2">
                <!-- Profile Card -->
                <div class="bg-white p-3 border-t-4 border-green-400">
                    <div class="image overflow-hidden">
                        {% for pqset in pqueryset  %}
                        {% if pqset.image %}
                        <img class="h-auto w-full mx-auto"
                            src="{{pqset.image.url}}"
                            alt="">
                        {% else %}
                        <img class="h-auto w-full mx-auto"
                            src="/Data/default.jpeg"
                            alt="">
                        {% endif %}
                    </div>
                    <h1 class="text-gray-900 font-bold text-xl leading-8 my-1 flex justify-between"> {{pqset.user}}<span><a href="{% url 'users:profile-update' %}"><button class="bg-yellow-500 py-1 px-2 rounded text-white text-sm">Edit Profile</button></a></span></h1>
                    <p class="text-sm text-gray-500 hover:text-gray-600 leading-6">{{pqset.about}}</p>
                    <ul
                        class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
                        <li class="flex items-center py-3">
                            <span>Member since</span>
                            <span class="ml-auto">{{pqset.user.date_joined}}</span>
                        </li>
                    </ul>
                </div>
                <!-- End of profile card -->
                <div class="my-4"></div>
                <!-- Friends card -->
                <!-- End of friends card -->
            </div>
            <!-- Right Side -->
            <div class="w-full md:w-9/12 mx-2 h-64">
                <!-- Profile tab -->
                <!-- About Section -->
                <div class="bg-white p-3 shadow-sm rounded-sm">
                    <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                        <span class="tracking-wide">About</span>
                    </div>
                    <div class="text-gray-700">
                        <div class="grid md:grid-cols-2 text-sm">
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Gender</div>
                                <div class="px-4 py-2">{{pqset.gender}}</div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Email.</div>
                                <div class="px-4 py-2">
                                    <a class="text-blue-800" href="{{pqset.user.email}}">{{pqset.user.email}}</a>
                                </div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Contact No.</div>
                                <div class="px-4 py-2">{{pqset.phone_no}}</div>
                            </div>
                            <div class="grid grid-cols-2 mt-1">
                                <div class="px-4 py-2 font-semibold">Change Password</div>
                                <a href="{% url 'password_change' %}"><button class="px-4 py-2 w-30 rounded bg-blue-500 text-white focus:outline-none hover:bg-blue-600 ">Change Password</button></a>

                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- End of about section -->

                <div class="my-4"></div>

                <!-- Experience and education -->
                    <!-- End of Experience and education grid -->
                </div>
                <!-- End of profile tab -->
            </div>
        </div>
    </div>
</div>
{% endblock body %}

users/templates/users/signup.html
{% extends "base.html" %}
{% block title %} Register {% endblock title %}

{% block body %}
    <div class="flex flex-col items-center pt-5 w-screen h-screen bg-gray-200 text-gray-700">
        {% if messages %}
        <div class="max-w-lg mx-auto">
            <div class="flex bg-yellow-100 rounded-lg p-4 mb-4 text-sm text-yellow-700" role="alert">
                <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                <div>
                    {% for msg in messages %}
                    <span class="font-medium">Info! </span> {{msg}}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <form class="flex flex-col bg-white rounded shadow-lg p-12" method="POST">
          {% csrf_token %}
                <label class="font-semibold text-xs" for="username">Username</label>
                <input class="flex items-center h-12 px-4 w-64 bg-gray-200 mt-2 rounded focus:outline-none focus:ring-2" type="text" name="username" >
                <label class="font-semibold text-xs" for="usernameField">Email</label>
                <input class="flex items-center h-12 px-4 w-64 bg-gray-200 mt-2 rounded focus:outline-none focus:ring-2"  type="email"  name="email" >
           
            <label class="font-semibold text-xs mt-3" for="password">Password</label>
            <input class="flex items-center h-12 px-4 w-64 bg-gray-200 mt-2 rounded focus:outline-none focus:ring-2"type="password" name="password" >
            <label class="font-semibold text-xs mt-3" for="confirm_password">Confirm Password</label>
            <input class="flex items-center h-12 px-4 w-64 bg-gray-200 mt-2 rounded focus:outline-none focus:ring-2"type="password" name="confirm_password" >
            <button class="flex items-center justify-center h-12 px-6 w-64 bg-blue-600 mt-8 rounded font-semibold text-sm text-blue-100 hover:bg-blue-700">Signup</button>
            <div class="flex mt-6 justify-center text-xs">
                <span class="mx-2 text-black-300">Already have an account? </span>
                <a class="text-blue-400 hover:text-blue-500" href="{% url 'login' %}">Sign In</a>
            </div>
        </form>
        <!-- Component End  -->
    </div>
{% endblock body %}