Funssignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('account/',include('users.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('password-change/',auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),name='password_change'),
    path('password-change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),name='password_change_done'),
]


urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

handler404 = "Funssignment.views.page_not_found_view"

index/urls.py
from django.urls import path
from . import views

app_name='index'

urlpatterns = [
    path('',views.index,name='index'),
    path('rules/',views.rules,name='rules'),
    path('quiz/<str:title>/',views.paginated_quiz,name='paginated_quiz'),
    path('mock/<int:post_id>/',views.quiz,name='quiz'),
    path('search/',views.search,name='search'),
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('contact/',views.contact,name='contact'),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.logout,name='logout'),
    path('profile-update/',views.profile_update,name='profile-update')
]

index/models.py
from django.db import models
from django.core.validators import validate_image_file_extension
from PIL import Image
from django.contrib.auth.models import User

subject_choices={
    ("Maths","Maths"),
    ("Physics","Physics"),
    ("Chemistry","Chemistry")
}

class QuizPost(models.Model):
    title=models.CharField(max_length=100,unique=True)
    desc=models.TextField(blank=True,null=False,default='No desc provided')
    subject=models.CharField(choices=subject_choices,max_length=15)
    thumbnail=models.ImageField(upload_to='Quiz-Thumbnail',default='default_quiz.jpeg',validators=[validate_image_file_extension])

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.thumbnail.path)

        if img.height > 300 or img.width > 300:
            output_size = (190, 163)
            img.thumbnail(output_size)
            img.save(self.thumbnail.path)

    class Meta:
        verbose_name_plural='QuizPost'

        
class Question(models.Model):
    ques_post=models.OneToOneField(QuizPost,on_delete=models.CASCADE)
    ques=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q_op1 = models.CharField(max_length=1,default='a',null=True)
    q_op2 = models.CharField(max_length=1,default='b',null=True)
    q_op3 = models.CharField(max_length=1,default='c',null=True)
    q_op4 = models.CharField(max_length=1,default='d',null=True)
    answer=models.CharField(max_length=1,blank=False)

    ques2=models.ImageField(upload_to='Quiz-Questions',default='default.jpeg',validators=[validate_image_file_extension])
    q2_op1 = models.CharField(max_length=1,default='a',null=True)
    q2_op2 = models.CharField(max_length=1,default='b',null=True)
    q2_op3 = models.CharField(max_length=1,default='c',null=True)
    q2_op4 = models.CharField(max_length=1,default='d',null=True)
    answer2=models.CharField(max_length=1,blank=False)

    ques3=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q3_op1 = models.CharField(max_length=1,default='a',null=True)
    q3_op2 = models.CharField(max_length=1,default='b',null=True)
    q3_op3 = models.CharField(max_length=1,default='c',null=True)
    q3_op4 = models.CharField(max_length=1,default='d',null=True)
    answer3=models.CharField(max_length=1,blank=False)

    ques4=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q4_op1 = models.CharField(max_length=1,default='a',null=True)
    q4_op2 = models.CharField(max_length=1,default='b',null=True)
    q4_op3 = models.CharField(max_length=1,default='c',null=True)
    q4_op4 = models.CharField(max_length=1,default='d',null=True)
    answer4=models.CharField(max_length=1,blank=False)

    ques5=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q5_op1 = models.CharField(max_length=1,default='a',null=True)
    q5_op2 = models.CharField(max_length=1,default='b',null=True)
    q5_op3 = models.CharField(max_length=1,default='c',null=True)
    q5_op4 = models.CharField(max_length=1,default='d',null=True)
    answer5=models.CharField(max_length=1,blank=False)

    ques6=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q6_op1 = models.CharField(max_length=1,default='a',null=True)
    q6_op2 = models.CharField(max_length=1,default='b',null=True)
    q6_op3 = models.CharField(max_length=1,default='c',null=True)
    q6_op4 = models.CharField(max_length=1,default='d',null=True)
    answer6=models.CharField(max_length=1,blank=False)

    ques7=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q7_op1 = models.CharField(max_length=1,default='a',null=True)
    q7_op2 = models.CharField(max_length=1,default='b',null=True)
    q7_op3 = models.CharField(max_length=1,default='c',null=True)
    q7_op4 = models.CharField(max_length=1,default='d',null=True)
    answer7=models.CharField(max_length=1,blank=False)

    ques8=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q8_op1 = models.CharField(max_length=1,default='a',null=True)
    q8_op2 = models.CharField(max_length=1,default='b',null=True)
    q8_op3 = models.CharField(max_length=1,default='c',null=True)
    q8_op4 = models.CharField(max_length=1,default='d',null=True)
    answer8=models.CharField(max_length=1,blank=False)

    ques9=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q9_op1 = models.CharField(max_length=1,default='a',null=True)
    q9_op2 = models.CharField(max_length=1,default='b',null=True)
    q9_op3 = models.CharField(max_length=1,default='c',null=True)
    q9_op4 = models.CharField(max_length=1,default='d',null=True)
    answer9=models.CharField(max_length=1,blank=False)

    ques10=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q10_op1 = models.CharField(max_length=1,default='a',null=True)
    q10_op2 = models.CharField(max_length=1,default='b',null=True)
    q10_op3 = models.CharField(max_length=1,default='c',null=True)
    q10_op4 = models.CharField(max_length=1,default='d',null=True)
    answer10=models.CharField(max_length=1,blank=False)

    ques11=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q11_op1 = models.CharField(max_length=1,default='a',null=True)
    q11_op2 = models.CharField(max_length=1,default='b',null=True)
    q11_op3 = models.CharField(max_length=1,default='c',null=True)
    q11_op4 = models.CharField(max_length=1,default='d',null=True)
    answer11=models.CharField(max_length=1,blank=False)

    ques12=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q12_op1 = models.CharField(max_length=1,default='a',null=True)
    q12_op2 = models.CharField(max_length=1,default='b',null=True)
    q12_op3 = models.CharField(max_length=1,default='c',null=True)
    q12_op4 = models.CharField(max_length=1,default='d',null=True)
    answer12=models.CharField(max_length=1,blank=False)

    ques13=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q13_op1 = models.CharField(max_length=1,default='a',null=True)
    q13_op2 = models.CharField(max_length=1,default='b',null=True)
    q13_op3 = models.CharField(max_length=1,default='c',null=True)
    q13_op4 = models.CharField(max_length=1,default='d',null=True)
    answer13=models.CharField(max_length=1,blank=False)

    ques14=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q14_op1 = models.CharField(max_length=1,default='a',null=True)
    q14_op2 = models.CharField(max_length=1,default='b',null=True)
    q14_op3 = models.CharField(max_length=1,default='c',null=True)
    q14_op4 = models.CharField(max_length=1,default='d',null=True)
    answer14=models.CharField(max_length=1,blank=False)

    ques15=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q15_op1 = models.CharField(max_length=1,default='a',null=True)
    q15_op2 = models.CharField(max_length=1,default='b',null=True)
    q15_op3 = models.CharField(max_length=1,default='c',null=True)
    q15_op4 = models.CharField(max_length=1,default='d',null=True)
    answer15=models.CharField(max_length=1,blank=False)

    ques16=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q16_op1 = models.CharField(max_length=1,default='a',null=True)
    q16_op2 = models.CharField(max_length=1,default='b',null=True)
    q16_op3 = models.CharField(max_length=1,default='c',null=True)
    q16_op4 = models.CharField(max_length=1,default='d',null=True)
    answer16=models.CharField(max_length=1,blank=False)

    ques17=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q17_op1 = models.CharField(max_length=1,default='a',null=True)
    q17_op2 = models.CharField(max_length=1,default='b',null=True)
    q17_op3 = models.CharField(max_length=1,default='c',null=True)
    q17_op4 = models.CharField(max_length=1,default='d',null=True)
    answer17=models.CharField(max_length=1,blank=False)

    ques18=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q18_op1 = models.CharField(max_length=1,default='a',null=True)
    q18_op2 = models.CharField(max_length=1,default='b',null=True)
    q18_op3 = models.CharField(max_length=1,default='c',null=True)
    q18_op4 = models.CharField(max_length=1,default='d',null=True)
    answer18=models.CharField(max_length=1,blank=False)

    ques19=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q19_op1 = models.CharField(max_length=1,default='a',null=True)
    q19_op2 = models.CharField(max_length=1,default='b',null=True)
    q19_op3 = models.CharField(max_length=1,default='c',null=True)
    q19_op4 = models.CharField(max_length=1,default='d',null=True)
    answer19=models.CharField(max_length=1,blank=False)

    ques20=models.ImageField(upload_to='Quiz-Questions',validators=[validate_image_file_extension])
    q20_op1 = models.CharField(max_length=1,default='a',null=True)
    q20_op2 = models.CharField(max_length=1,default='b',null=True)
    q20_op3 = models.CharField(max_length=1,default='c',null=True)
    q20_op4 = models.CharField(max_length=1,default='d',null=True)
    answer20=models.CharField(max_length=1,blank=False)

    def __str__(self):
        return str(self.ques_post)

class Result(models.Model):
    post=models.ForeignKey(Question,on_delete=models.CASCADE)
    score=models.CharField(max_length=5)
    correct=models.CharField(max_length=5)
    wrong=models.CharField(max_length=5)
    not_attempted=models.CharField(max_length=5)
    result_of=models.ForeignKey(User,on_delete=models.CASCADE)

index/templates/index/home.html
{% extends "base.html" %}
{% block title %} Funssignment {% endblock title %}
<style>
@media screen and (max-width:800px){
  .search-br{
    margin-left: 50px;
  }
}
</style>
{% block body %}
  <!-- component -->
  <!-- component -->
<!-- This is an example component -->
<div class="pt-2 text-gray-600 ml-14">
    <form method="post" action="{% url 'index:search' %}" >
      {% csrf_token %}
    <input class="border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none"
      type="search" name="searched" placeholder="Search">
    <button type="submit" class="pt-5 mr-5">
      <svg class="text-gray-600 h-4 w-4  fill-current" xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
        viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
        width="512px" height="512px">
        <path
          d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
      </svg>
    </button>
</form>
  </div>
{% if messages %}
{% for msg in messages %}
<div class="px-4 py-3 leading-normal text-white bg-green-500 border" role="alert">
    <p>{{msg}}</p>
</div>
{% endfor %}
{% endif %}
<section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for q2 in qset %}
        <div class="w-full bg-white rounded-lg sahdow-lg overflow-hidden flex flex-col justify-center items-center">
            <a href="{% url 'index:paginated_quiz' q2.title %}">
            <div class="card-div ">
                {% if q2.thumbnail %}
                <img class="w-full h-full" src="{{q2.thumbnail.url}}" alt="photo">
                {% else %}
                {% if q2.subject == "Physics" %}
                <img class="object-center object-cover h-auto w-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" alt="photo">
                {% elif q2.subject == "Maths" %}
                <img class="object-center object-cover h-auto w-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" alt="photo">
                {% elif q2.subject == "Chemistry" %}
                <img class="object-center object-cover h-auto w-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" alt="photo">
                {% endif %}
                {% endif %}
            </div>
            <div class="text-center py-8 sm:py-6">
                <p class="text-xl text-gray-700 font-bold mb-2">{{q2.title}}</p>
                <p class="text-base text-gray-400 font-normal">{{q2.subject}}</p>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock body %}

<!--<img class="object-center object-cover h-auto w-full" src="/Data/default_quiz.jpeg" alt="photo"-->

index/templates/index/paginated_quiz.html
{% extends "base.html" %}
{% block title %} Home-Funssignment {% endblock title %}
{% block body %}

<!-- component -->
<div class="mt-6 bg-gray-50">
    <div class=" px-10 py-6 mx-auto card-div">
          
          <!--author-->
          {% for qset in queryset %}
       <div class="max-w-2xl px-10 mx-auto bg-gray-50">
          <a href="" class="block transition duration-200 ease-out transform">
              {% if qset.thumbnail %}
              <img class="w-full shadow-sm card-div" src="{{qset.thumbnail.url}}" alt="photo">
              {% else %}
                 {% if q2.subject == "Physics" %}
                <img class="object-cover w-full shadow-sm h-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" alt="photo">
                {% elif q2.subject == "Maths" %}
                <img class="object-cover w-full shadow-sm h-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" alt="photo">
                {% elif q2.subject == "Chemistry" %}
                <img class="object-cover w-full shadow-sm h-full" src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" alt="photo">
                {% endif %}
                {% endif %}
          </a>

          <div class="mt-2 flex flex-row justify-between align-center pl-4 pr-4">
              <!--post heading-->
              <a href=""
                  class="sm:text-3xl md:text-3xl lg:text-3xl xl:text-4xl font-bold text-purple-500 ml-6 hover:underline">{{qset.title}}</a> 
             {% if user.is_authenticated %}     
             {% if qset.question %}<a href="{% url 'index:quiz' qset.question.id %}">  <button class="p-2 bg-blue-500 hover:bg-blue-600 rounded text-white w-full">Start</button></a>
             {% else %} <button class="p-2 bg-blue-500 hover:bg-blue-600 rounded text-white w-full">Coming soon</button></a>
             {% endif %}
             {% else %}
             <a href="{% url 'login'%}">  <button class="p-2 bg-blue-500 hover:bg-blue-600 rounded text-white w-full">Login</button></a>
             {% endif %}
                  <!--post views-->
                  <!--author avator-->
         </div>
      
         <!--end post header-->
              <!--post content-->
   <div class="max-w-4xl mx-auto text-2xl text-gray-700 text-left mt-4 ml-8 rounded bg-gray-100">

       <!--content body-->
       <div>
        {% if qset2.desc %}<p class="mt-2">{{qset2.desc}}{% else %} No desc {% endif %}</p>
       </div>
          </div>
      </div>
      {% endfor %}
      <!--related posts-->
<h2 class="text-2xl mt-4 text-gray-500 font-bold text-center">Related Posts</h2>
<div class="flex grid h-full grid-cols-12 gap-10 pb-10 mt-8 sm:mt-16">


<div class="grid grid-cols-12 col-span-12 gap-7">
    {% for post in post_query  %}

  <div class="flex flex-col items-start col-span-12 overflow-hidden shadow-sm rounded-xl md:col-span-6 lg:col-span-4">
      <a href="{% url 'index:paginated_quiz' post.title %}" class="transition duration-200 ease-out transform">
          <img class="object-center w-full shadow-sm" src="{{post.thumbnail.url}}">
      </a>
      <div class="relative flex flex-col items-start px-6 bg-white border border-t-0 border-gray-200 w-full py-7">
          <h2 class="text-center text-gray-500 font-bold sm:text-lg md:text-xl"><a href="{% url 'index:paginated_quiz' post.title %}">{{post.title}}</a></h2>
      </div>
  </div>
    {% endfor %}
</div>
</div>
</div>
</div>
{% endblock body %}

index/templates/index/profile_update.html
{% extends "base.html" %}
{% block title %}Profile-Update{% endblock title %}
{% block body %}
{% load crispy_forms_tags %}

    <div class="bg-gray-100">
 <div class="w-full text-white bg-main-color">
        <div x-data="{ open: false }"
            class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
            <div class="p-6 flex flex-row items-center justify-between">
               
                <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
                    <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                        <path x-show="!open" fill-rule="evenodd"
                            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"
                            clip-rule="evenodd"></path>
                        <path x-show="open" fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </div>
    <div class="container mx-auto my-5 p-5">
        <div class="md:flex no-wrap md:-mx-2 ">
            <!-- Left Side -->
            <div class="w-full md:w-3/12 md:mx-2">
                <!-- Profile Card -->
                <div class="bg-white p-3 border-t-4 border-green-400">
                    <div class="image overflow-hidden">
                {% if queryset_update %}
                        {% if queryset_update.image %}
                        <img class="h-auto w-full mx-auto"
                            src="{{queryset_update.image.url}}"
                            alt="">
                        {% else %}
                        <img class="h-auto w-full mx-auto"
                            src="/Data/default.jpeg"
                            alt="">
                        {% endif %}
                        
                    </div>
                    <h1 class="text-gray-900 font-bold text-xl leading-8 my-1">{{queryset_update.user.username}}</h1>
                    <p class="text-sm text-gray-500 hover:text-gray-600 leading-6">{{queryset_update.about}}</p>
                </div>
                {% endif %}
                <!-- End of profile card -->
                <div class="my-4"></div>
                <!-- Friends card -->
                <!-- End of friends card -->
            </div>
            <!-- Right Side -->
            <div class="w-full md:w-9/12 mx-2 h-64">
                <!-- Profile tab -->
                <!-- About Section -->
                <div class="bg-white p-3 shadow-sm rounded-sm">
                    <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                        <span clas="text-green-500">
                            <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </span>
                        <form method="post">
                            {% csrf_token %}
                            {{form |crispy}}
                            <a href="{% url 'users:profile' %}"><button class="px-4 py-2 w-30 rounded bg-blue-500 text-white focus:outline-none hover:bg-blue-600 ">Update Profile</button></a>
                            </form>
                    </div>
                </div>
                <!-- End of about section -->

                <div class="my-4"></div>    
                    </div>
                    <!-- End of Experience and education grid -->
                </div>
                <!-- End of profile tab -->
            </div>
        </div>
    </div>
</div>
{% endblock body %}

index/templates/index/result.html
{% extends "base.html" %}
{% load static %}
{% block script %}<link rel="stylesheet" href="{% static 'css/result.css' %}"/> {% endblock script %}
{% block title %}Result {% endblock title %}
{% block body %}
  <div>
    <table class="w-full flex flex-row flex-no-wrap sm:bg-white text-center rounded-lg overflow-hidden sm:shadow-lg mt-5 text-center">
 
      <thead class="text-black">
        {% for ques_queryset in queryset.result_set.all  %} 
            <tr class="bg-lime-500 flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                <th class="p-3">Name</th>
                <th class="p-3">Correct Answer</th>
                  <th class="p-3">Wrong Answer</th>
                  <th class="p-3">Not Attempted</th>
                <th class="p-3" >Score</th>
            </tr>
            
          {% endfor %}
          </thead>
        <tbody class="flex-1 sm:flex-none ">
          {% for ques_queryset in queryset.result_set.all  %} 
            <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0">
                <td class="border-grey-light border hover:bg-gray-100 p-3">{{ques_queryset.result_of}}</td>
                <td class="border-grey-light border hover:bg-gray-100 p-3">{{ques_queryset.correct}}</td>
                <td class="border-grey-light border hover:bg-gray-100 p-3">{{ques_queryset.wrong}}</td>
                <td class="border-grey-light border hover:bg-gray-100 p-3">{{ques_queryset.not_attempted}}</td>
                <td class="border-grey-light border hover:bg-gray-100 p-3">{{ques_queryset.score}}/80</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div>
{% endblock body %}